AWSTemplateFormatVersion: "2010-09-09"
Description: >
  An example of a user, role and direct calls to AssumeRole and STS to get a
  temporary token

Resources:
  ExampleUser:
    Type: AWS::IAM::User
    Properties:
      UserName: 'sts-prototype-user'

  AccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref ExampleUser

  ExampleRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'sts-prototype-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: 'Allow'
            Principal:
              AWS:
                - !GetAtt ExampleUser.Arn
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - !Ref ExamplePolicy

  ExamplePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: 'sts-prototype-policy'
      Description: 'Gives access to an S3 bucket to test STS'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: 'Allow'
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
            Resource: !Join ['/', [ !GetAtt ExampleBucket.Arn, '*' ]]

  ExampleBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'sts-prototype-bucket'

Outputs:
  AccessKeyId:
    Value: !Ref AccessKey
  SecretAccessKey:
    Value: !GetAtt AccessKey.SecretAccessKey
  ExampleRoleArn:
    Value: !GetAtt ExampleRole.Arn
